apiVersion: v1
kind: Service
metadata:
  name: python-game-service
spec:
  selector:
    app: python-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
